name: f0Ring
version: 1.0.0
main: me.f0rant.f0ring.F0Ring
api-version: '1.21'
authors: [f0rant]
commands:
  ring:
    description: Opens the ring selection menu.
    usage: /ring
    aliases: [ringo, f0ring]